title: "Cloth Manipulation Challenge"
description: "Website for the research paper."
remote_theme: daviddarnes/alembic

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional tweaks:
author: Irene Garcia-Camacho
lang: en
