title: Cloth Manipulation and Perception Competition
description: Cloth Manipulation and Perception Competition official website
author: Irene Garcia-Camacho
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
